config/routes.rb
Rails.application.routes.draw do
  root "web_reservations#status"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  resources :items, only: [:index]
  resources :web_reservations, only: [:index, :show, :new, :create] do
    collection do
      get :status
    end
  end
  controller :api do
    post 'api/sign_in'
    delete 'api/sign_out'
    get 'api/master_updated_at'
    post 'api/upsert_items'
    get 'api/mng_reservation_id_updated_at'
    post 'api/upsert_mng_reservations'
    post 'api/destroy_mng_reservations'
    get 'api/web_reservation_ids'
    get 'api/web_reservation'
    post 'api/update_web_reservation'
  end
end

app/models/web_reservation.rb
# ※新規生成のみで編集はしない
class WebReservation < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :mng_reservation
  # 削除時は0にする
  validates :number, numericality: {greater_than_or_equal_to: 0}

  include StartEndDateHolder

  validate :validate_start_date
  validate :validate_item_stock

  before_save do
    self.reservation_name = "#{self.item.item_name} x #{self.number}：#{self.start_end_date_to_s}"
    self.reservation_date = Date.today if self.reservation_date.nil?
  end

  scope :has_not_mng, -> {left_joins(:mng_reservation).where('mng_reservations.id IS NULL')}

  def update_mng_linkage(h_web, h_mng)
    WebReservation.transaction do
      self.attributes = h_web
      if h_web.present?
        # 生成済みでもIDが異なるなら削除
        if self.mng_reservation.present? && (h_mng.blank? || self.mng_reservation.id.to_s != h_mng['id'].to_s)
          puts "mng_reservation re-created #{self.mng_reservation.id}"
          self.mng_reservation.destroy
          self.mng_reservation = nil
        end

        if self.mng_reservation.present?
          puts "web_reservation.mng_reservation.present? true #{self.mng_reservation.id}"
          self.mng_reservation.attributes = h_mng
          self.mng_reservation.save!
        elsif h_mng.present?
          puts "web_reservation.mng_reservation.present? false"
          self.mng_reservation = MngReservation.new(h_mng)
          self.mng_reservation.save!
        end

      # 予約情報が消えた場合
      elsif self.mng_reservation.present?
        puts "web_reservation.mng_reservation destroy #{self.mng_reservation.id}"
        self.mng_reservation.destroy
        self.mng_reservation = nil
      end
      save
    end
  end

  private
    def validate_start_date
      errors.add(:start_date, 'は本日以降を選択してください') if start_date < Date.today
    end
    def validate_item_stock
      if number > 0
        map = ReservedMap.new(item, start_date, end_date)
        errors.add(:item_id, 'は予約一杯の日付があります') unless map.permit_all?(number)
      end
    end
end

app/controllers/web_reservations_controller.rb
class WebReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_web_reservation, only: [:show]

  def index
    @web_reservations = current_user.web_reservations.order(created_at: :desc).page(params[:page]).per(20)
  end

  def show
  end

  def status
    date_from = params[:date_from]
    @date_from = date_from.present? ? Date.parse(date_from) : Date.today
    # 開始日付は必ず今日以降
    @date_from = Date.today if @date_from < Date.today
    @date_to = @date_from + 6
    @items = Item.all
  end

  def new
    @web_reservation = WebReservation.new
  end

  def create
    @web_reservation = current_user.web_reservations.build(web_reservation_params)
    @web_reservation.reservation_date = Date.today

    if @web_reservation.save
      redirect_to web_reservations_url, notice: 'アイテムを予約しました。'
    else
      render :new
    end
  end

  private
    def set_web_reservation
      @web_reservation = WebReservation.find(params[:id])
    end
    def web_reservation_params
      params.require(:web_reservation).permit(:item_id, :number, :start_date, :end_date)
    end
end

app/views/web_reservations/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@web_reservation) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    .row
      .col-lg-6
        = f.association :item, label_method: :item_name, include_blank: false
      .col-lg-6
        = f.input :number, input_html: {min: 1}
    .row
      .col-lg-5
        = f.input :start_date, as: :date, html5: true
      .col-lg-2.d-flex.align-items-center.text-center
        %span.mx-auto ～
      .col-lg-5
        = f.input :end_date, as: :date, html5: true

  .form-actions.text-center
    = f.button :submit, class: 'btn btn-primary'

app/views/web_reservations/index.html.haml
%h2 アイテム予約履歴

%table.table
  %thead.thead-light
    %tr
      %th{ scope: 'col' } ID
      %th{ scope: 'col' } アイテム名
      %th{ scope: 'col' } 数量
      -# %th{ scope: 'col' } 予約名
      %th{ scope: 'col' } 予約日
      %th{ scope: 'col' } 開始日
      %th{ scope: 'col' } 終了日
      %th

  %tbody
    - @web_reservations.each do |web_reservation|
      - reservation = web_reservation.mng_reservation.present? ? web_reservation.mng_reservation : web_reservation
      %tr
        %td= reservation.id
        %td= reservation.item.item_name
        %td= reservation.number
        -# %td= reservation.reservation_name
        %td= reservation.reservation_date.strftime("%Y/%m/%d")
        %td= reservation.start_date.strftime("%Y/%m/%d")
        %td= reservation.end_date.strftime("%Y/%m/%d")
        %td= link_to '表示', web_reservation, class: 'btn btn-outline-dark btn-sm'
= paginate @web_reservations

app/views/web_reservations/new.html.haml
%h2 新しい予約

= render 'form'

= link_to '戻る', web_reservations_path, class: 'btn btn-outline-secondary'

app/views/web_reservations/show.html.haml
%h2
  予約の詳細
  = @web_reservation.mng_reservation.present? ? '(承認済)' : ''

- reservation = @web_reservation.mng_reservation.present? ? @web_reservation.mng_reservation : @web_reservation
.row.mb-3
  .col-6.p-1
    .card
      .card-header アイテム名
      .card-body= reservation.item.item_name
  .col-6.p-1
    .card
      .card-header 数量
      .card-body= reservation.number
.card.mb-3
  .card-header 予約名
  .card-body= reservation.reservation_name
.card.mb-3
  .card-header 予約日
  .card-body= reservation.reservation_date.strftime("%Y/%m/%d")
.row.mb-3
  .col-6.p-1
    .card
      .card-header 開始日
      .card-body= reservation.start_date.strftime("%Y/%m/%d")
  .col-6.p-1
    .card
      .card-header 終了日
      .card-body= reservation.end_date.strftime("%Y/%m/%d")

= link_to '戻る', web_reservations_path, class: 'btn btn-outline-secondary'

app/views/web_reservations/status.html.haml
%h2 アイテムの予約状況（予約数 / アイテム数）

.row.align-items-center
  .col-lg-4.text-right
    = link_to "<<", status_web_reservations_path(date_from: (@date_from - 7)), class: 'btn btn-outline-secondary'
    = link_to "<", status_web_reservations_path(date_from: (@date_from - 1)), class: 'btn btn-outline-secondary'
  .col-lg-4.text-center
    = form_with(url: status_web_reservations_path, method: :get, local: true, class: 'simple_form') do |f|
      = f.date_field :date_from, value: @date_from, class: 'form-control mx-1'
  .col-lg-4.text-left
    = link_to ">", status_web_reservations_path(date_from: (@date_from + 1)), class: 'btn btn-outline-secondary'
    = link_to ">>", status_web_reservations_path(date_from: (@date_from + 7)), class: 'btn btn-outline-secondary'

%table.table.table-bordered.table-sm
  %thead.thead-light
    %tr
      %th.align-middle.text-center{style: "width:30%"} アイテム名
      - (@date_from..@date_to).each do |date|
        %th.align-middle.text-center{style: "width:10%"}= date_to_s_with_wday(date)
  %tbody
    - @items.each do |item|
      - map = ReservedMap.new(item, @date_from, @date_to)
      %tr
        %td.align-middle.text-center= item.item_name
        - (@date_from..@date_to).each do |date|
          = td_rate_tag(map.reserved(date), item.stock)

= link_to '新しい予約', new_web_reservation_path, class: 'btn btn-primary'